### ISSUE TITLE
Archive this repo?

### ISSUE THREAD

**Issue by sloria** [4Catalyzer/python#21]
We now rely mostly on fourmat for enforcing style. At this point it probably makes sense to archive this repo and document any non-automated guidelines in Notion?

wdyt @itajaja @taion

**Comment by taion** [comment]
See my comment in Slack – the nice thing about having this repo is that it's accessible to people throughout 4C, though, as opposed to just Butterfly folks.

**Comment by sloria** [comment]
Yep, good point. I just copied my updates in Notion into https://github.com/4Catalyzer/python/pull/22 . So Notion will just have a link to this repo + bfly-specific stuff.
